# ============= #
# Site settings #
# ============= #
title: Personal website
description: Jekyll static website
url: https://serphyus.github.io

# ============= #
# User settings #
# ============= #
fullname: Sigurd Pettersen
username: Serphyus
user_title: Cybersecurity Student
email: serphyus@gmail.com
# twitter_username: username
# instagram_username: username
# facebook_username: username
linkedin_username: sigurd-pettersen-a24705233
github_username:  serphyus
# medium_username: username
# medium_url: username
# gplus_username: username

exclude: ['src']