# ============= #
# Site settings #
# ============= #

title: Sigurd Pettersen
description: Jekyll static website
url: https://serphyus.github.io


# ============= #
# User settings #
# ============= #

fullname: Sigurd Pettersen
first_name: Sigurd
last_name: Pettersen
username: Serphyus
user_title: Cybersecurity student & software developer

email: serphyus@gmail.com
linkedin_username: sigurd-pettersen-a24705233
github_username:  serphyus


# ============= #
# Misc Settings #
# ============= #

exclude: ['src']